version: '3.3'

services:

  mongodb:
    image: mongo
    volumes:
      - ./api-provider/mongodb/:/data/db
    ports:
      - "27017:27017"

  baycakes-provider:
    image: baycakes-provider
    build: ./api-provider
    ports:
      - "8080:8080"
    links:
      - mongodb

#  baycakes-consumer:
#    image: baycakes-consumer
#    build: ./api-consumer
#    ports:
#      - "8081:8081"
#    links:
#      - baycakes-provider
