spring:
  jpa:
    show-sql: false
    database: h2
    hibernate:
      use-new-id-generator-mappings: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    ROOT: INFO

server:
  port: 8181

baycakes:
  token:
    header: X-Auth-Token
    secret: baycakes-secret
    expiration: 604800
  route:
    authentication: auth
    authentication.refresh: refresh
