spring:
  jpa:
    show-sql: false
    hibernate:
      use-new-id-generator-mappings: true
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: baycakes
  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    ROOT: INFO

baycakes:
  token:
    header: X-Auth-Token
    secret: baycakes-secret
    expiration: 604800
  route:
    authentication: auth
    authentication.refresh: refresh
