spring:
  jpa:
    show-sql: false
    database: h2
    hibernate:
      use-new-id-generator-mappings: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: baycakes
  jackson:
    serialization:
      INDENT_OUTPUT: true
